---
# tasks file for ansible-role-clickhouse-server/

- name: Add apt repo keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id:        E0C56BD4
    state:     present

- name: Add Clickhouse repo
  apt_repository:
    repo:  deb http://repo.yandex.ru/clickhouse/deb/stable/ main/
    state: present

- name: Install cliclhouse-server package
  apt:
    name:         clickhouse-server
    state:        latest
    update_cache: yes

- name: Ensure clickhouse server in running and enabled on startup
  service:
    name:    clickhouse-server
    state:   started
    enabled: yes